
# name: List of all default Github Vars

# on:
#   push:
#     branches: [ "main"]
#   workflow_dispatch:


# jobs:
#   ubuntu-environment-variables:
#     runs-on: ubuntu-latest
#     steps:
#       - run: env

#   windows-environment-variables:
#     runs-on: windows-latest
#     steps:
#     - run: env

#   macos-enironment-variables:
#     runs-on: macos-latest
#     steps:
#     - run: env


name: 'Default environment variables'

on:
  push:
    branches: [ "main" ]

jobs:
  mainjob:
    name: 'print the Default Github variables'
    runs-on: ubuntu-latest

    steps:
    - name: print-values-of-env-vars
      run: 
        echo "$GITHUB_ACTION"
        echo "$GITHUB_ENV"
        echo "$GITHUB_API_URL"
        echo "$GITHUB_JOB"
        echo "$GITHUB_PATH"
        echo "$GITHUB_STEP_SUMMARY"
        echo "$GITHUB_WORKFLOW"
        echo "$GITHUB_REPOSITORY_OWNER"
        echo "$GITHUB_RUN_NUMBER"
        echo "$GITHUB_SERVER_URL"
        echo "$RUNNER_NAME"